I'll research the causes of AMD and identify credible herbal, nutritional, and supplement-based approaches that may help slow its progression. I'll focus on traditional remedies that have stood the test of time as well as modern medical research to ensure credibility.

I'll get back to you with a well-rounded summary of potential therapies.

# Age-Related Macular Degeneration: Causes and Nutritional Therapies

**Age-related macular degeneration (AMD)** is a complex eye disease driven by multiple factors, including genetics, oxidative stress, inflammation, and circulatory issues in the retina. Understanding these underlying causes helps guide nutritional and herbal strategies to slow AMD’s progression. Below, we explore the causes of AMD and evidence-based dietary, supplement, and herbal interventions – from key vitamins to historically used herbs – that can help protect the macula. Each recommendation is grounded in peer-reviewed research and traditional practices, with mechanisms explaining how they benefit retinal health.

## Underlying Causes of AMD (Genetic, Oxidative, Inflammatory, Circulatory)

- **Genetic Susceptibility**: A family history of AMD increases risk, and researchers have identified specific gene variants that predispose individuals to AMD. Notably, mutations in genes of the **complement immune system** (such as *complement factor H* and others) are strongly linked to AMD ([
            Age-Related Macular Degeneration: Role of Oxidative Stress and Blood Vessels - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7866075/#:~:text=which%20independently%20leads%20to%20the,CFB%29%2C%20and)). These genetic factors can heighten the retina’s vulnerability to damage by influencing inflammatory pathways and oxidative stress responses ([
            Age-Related Macular Degeneration: Role of Oxidative Stress and Blood Vessels - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7866075/#:~:text=mentioned%20above%2C%20mtDNA%20damage%20in,been%20strongly%20associated%20with%20AMD)) ([
            Age-Related Macular Degeneration: Role of Oxidative Stress and Blood Vessels - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7866075/#:~:text=found%20a%20significant%20association%20between,144)). However, having a risk gene doesn’t guarantee AMD – it means one should be more mindful of other modifiable factors like diet and smoking.

- **Oxidative Stress**: The retina has one of the highest metabolic rates in the body and is exposed to intense light, making it an **ideal environment for reactive oxygen species (ROS) generation** ([
            Age-Related Macular Degeneration: Role of Oxidative Stress and Blood Vessels - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7866075/#:~:text=cause%20oxidative%20stress%20)). Over time, this oxidative stress damages retinal cells. Photoreceptors and the retinal pigment epithelium (RPE) accumulate waste products (like *lipofuscin* pigment); when exposed to blue light, these can form singlet oxygen and wreak havoc on RPE cells ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=glutathione%20peroxidase%20in%20human%20retinal,be%20an%20important%20factor%20in)). In AMD, oxidative damage leads to the death of RPE and photoreceptors, contributing to drusen formation and retinal degeneration ([
            Age-Related Macular Degeneration: Role of Oxidative Stress and Blood Vessels - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7866075/#:~:text=photooxidative%20stress%20may%20damage%20cellular,63)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=glutathione%20peroxidase%20in%20human%20retinal,be%20an%20important%20factor%20in)). **Smoking** dramatically exacerbates oxidative stress and roughly doubles the risk of AMD, while lifelong antioxidant deficiencies can leave the macula vulnerable ([
            Age-Related Macular Degeneration: Role of Oxidative Stress and Blood Vessels - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7866075/#:~:text=ethnicity%29%2C%20epidemiological%20risk%20factors%20%28body,especially%20owing%20to%20the%20much)). Overall, oxidative stress is considered a key driver of AMD pathology ([
            Age-Related Macular Degeneration: Role of Oxidative Stress and Blood Vessels - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7866075/#:~:text=environmental%20risk%20factors%20,especially%20owing%20to%20the%20much)).

- **Chronic Inflammation**: The damage from oxidative stress often triggers a local inflammatory response in the retina. Drusen (the yellow deposits under the retina that are a hallmark of AMD) contain inflammatory proteins and complement components, reflecting ongoing **immune system activation**. In fact, higher systemic inflammatory markers and complement dysregulation are associated with AMD progression ([
            Age-Related Macular Degeneration: Role of Oxidative Stress and Blood Vessels - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7866075/#:~:text=ethnicity%29%2C%20epidemiological%20risk%20factors%20%28body,especially%20owing%20to%20the%20much)). The same complement gene variants mentioned above lead to an overactive immune response in the macula, causing friendly-fire damage to retinal cells. **Microglia** (immune cells in the retina) can become activated and release cytokines that further injure the tissue. Thus, AMD can be viewed in part as a chronic, smoldering inflammation in the macula ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=possess%20antinflammatory%20and%20antiapoptotic%20effects%2C,exact%20mechanism%20as%20peculiar%20characteristics)). Controlling this inflammation – via diet or supplements – is an important therapeutic target.

- **Circulatory Factors**: The retina depends on the underlying choroidal blood vessels for oxygen and nutrients. In AMD, especially the dry form, there is often **choroidal vascular dysfunction** – reduced perfusion of the macula and atherosclerotic changes in the tiny vessels ([
            Age-Related Macular Degeneration: Role of Oxidative Stress and Blood Vessels - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7866075/#:~:text=Age,for%20patients%20suffering%20from%20AMD)) ([
            Age-Related Macular Degeneration: Role of Oxidative Stress and Blood Vessels - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7866075/#:~:text=environmental%20risk%20factors%20,especially%20owing%20to%20the%20much)). Impaired blood flow means retinal cells don’t clear waste or get nutrients efficiently, compounding damage. In advanced “wet” AMD, new abnormal blood vessels grow (neovascularization) but they are leaky and cause bleeding/fluid that damages central vision. Vascular endothelial growth factor (VEGF) drives this process. Systemic cardiovascular risk factors like hypertension and high cholesterol are linked to AMD, likely through their effect on the eye’s circulation. Conversely, what’s good for the heart (exercise, healthy diet, not smoking) is also good for the retinal vessels. *In summary:* genetics loads the gun, but oxidative stress (often from smoking or poor diet) and inflammation pull the trigger – and poor circulation in the aging eye sets the stage for damage. This understanding has led to therapies emphasizing **antioxidants, anti-inflammatories, and circulatory support** for AMD management.

## Nutritional Strategies for AMD Prevention and Management

 ([270+ Healthy Food Pictures | Download Free Images & Stock Photos on Unsplash](https://unsplash.com/s/photos/healthy-food)) *A balanced, antioxidant-rich diet (colorful vegetables, leafy greens, fruits, and healthy fats) provides nutrients that protect the macula from degeneration.* Proper nutrition is one of the most powerful tools to slow AMD. Large reviews have found that people with high intake of certain nutrients have significantly lower risk of AMD progression ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=Using%20the%20Grading%20of%20Recommendations%2C,of%20early%20to%20late%20AMD)). The key dietary components for macular health include:

- **Leafy Greens and Colorful Vegetables**: Dark leafy greens like **kale, spinach, collards, and broccoli** are packed with *lutein and zeaxanthin*, the two carotenoid pigments that directly accumulate in the macula ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=tissues%20and%20biological%20fluids,activities%20and%20functions%2C%20which%20are)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=%CE%B2,much%20more%20effective%20antioxidant%2C%20is)). These pigments act as a natural blue-light filter and as antioxidants in retinal tissue. In fact, lutein and zeaxanthin concentrations in the macula are about 1000× higher than in other tissues, forming the protective macular pigment ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=pigment%20of%20the%20central%20macula,the%20dominant%20component%20in%20the)). Diets rich in these carotenoids (also found in peas, squash, corn, orange peppers, etc.) are associated with a lower risk of AMD ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=Using%20the%20Grading%20of%20Recommendations%2C,of%20early%20to%20late%20AMD)). Mechanistically, lutein has excellent light-filtering ability, while zeaxanthin is a potent quencher of singlet oxygen; together they neutralize oxidative damage in photoreceptors ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=correlated%20with%20their%20retinal%20spatial,These)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=level%20%28Bungau%20et%20al,has%20been%20reported%20that%20lutein)). They also activate the Nrf2 pathway in retinal cells, boosting the cells’ own antioxidant enzymes ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=cell%20layer%20from%20light,Some)). **Practical tip:** Aim for at least 2 servings of leafy greens daily – for example, a spinach salad or sautéed kale – and a variety of orange/yellow veggies each week. 

- **Omega-3 Fatty Acids (Fish)**: Cold-water fish (salmon, sardines, mackerel, tuna) provide **DHA and EPA**, the long-chain omega-3 fatty acids that are crucial for retinal health. DHA is a structural fat in photoreceptor membranes, and both DHA/EPA have anti-inflammatory effects. Observational studies show that higher dietary omega-3 intake correlates with a significantly lower risk of advanced AMD ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=Using%20the%20Grading%20of%20Recommendations%2C,of%20early%20to%20late%20AMD)). One analysis found up to a 38% reduction in late AMD risk in those eating the most omega-3-rich fish compared to those eating the least ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=Using%20the%20Grading%20of%20Recommendations%2C,of%20early%20to%20late%20AMD)) ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=In%20addition%2C%20use%20of%20antioxidant,intake%20of%20calcium%20or%20lycopene)). Omega-3s may stabilize cell membranes and reduce aberrant blood vessel growth in the retina by dampening inflammation. While the large AREDS2 trial did *not* find a benefit from omega-3 **supplements** alone ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=1,which%20increases%20lung%20cancer%20risk)), the consensus is that **eating fish twice a week** as part of a balanced diet is protective for both eyes and heart. For vegetarians or others, plant sources like flaxseed, chia, or walnuts provide alpha-linolenic acid (ALA) which partially converts to omega-3s, though not as efficiently.

- **Fruits and Other Vegetables**: A broad array of fruits (berries, oranges, kiwis) and vegetables (carrots, sweet potatoes, bell peppers, tomatoes) provide **vitamin C, beta-carotene, and other antioxidants** that support the macula. Vitamin C is concentrated in eye tissues and helps regenerate other antioxidants; vitamin A (from beta-carotene in orange produce) is essential for photoreceptor function. A diet high in vitamin C, beta-carotene, *and* other nutrients like magnesium and copper is linked to lower AMD risk ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=Using%20the%20Grading%20of%20Recommendations%2C,of%20early%20to%20late%20AMD)). Colorful berries (blueberries, blackberries) are rich in **polyphenols and anthocyanins**, which have shown protective effects on retinal cells by scavenging free radicals and bolstering antioxidant enzymes ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=retina%2C%20the%20portion%20of%20the,of%20superoxide%20dismutase%2C%20catalase%20and)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=also%20shown%20that%20bilberry%20anthocyanins,and%20damage)). For example, anthocyanins from blueberries can reduce oxidative stress in RPE cells and even prevent the buildup of toxic retinal pigments ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=blueberry%20anthocyanin%20extract%2C%20and%20some,A2E%20cannot%20be%20enzymatically%20degraded)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=and%20accumulates%20in%20the%20RPE,had%20macular%20degeneration%2C%20while%20bilberry)). The general rule is “eat the rainbow” – a variety of colors ensures you get a spectrum of protective compounds. Not coincidentally, this aligns with a **Mediterranean-style diet**, which has been associated with a slower progression of AMD ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=In%20addition%2C%20use%20of%20antioxidant,intake%20of%20calcium%20or%20lycopene)). One review noted that high consumption of vegetables, legumes, whole grains, and nuts (all staples of the Mediterranean diet) was linked to decreased risk of developing advanced AMD ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=In%20addition%2C%20use%20of%20antioxidant,intake%20of%20calcium%20or%20lycopene)).

- **Nuts, Seeds, and Healthy Fats**: **Nuts and seeds** are rich in vitamin E, zinc, and healthy fats. Vitamin E is a fat-soluble antioxidant that protects cell membranes in the retina from oxidative damage. The AREDS research identified vitamin E (400 IU/day) as a key nutrient to slow AMD progression ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=Commercially%20available%20formulas%20based%20on,Zinc%2080%20mg%2080%20mg)). Almonds, sunflower seeds, hazelnuts, and peanuts are excellent natural sources. These foods also provide **zinc**, a mineral highly concentrated in the retina and RPE. Zinc is a cofactor for antioxidant enzymes (like superoxide dismutase) and supports the immune system; inadequate zinc can worsen macular degeneration. In fact, 80 mg of zinc was used in the AREDS formula because it significantly helped reduce AMD progression ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=Commercially%20available%20formulas%20based%20on,Zinc%2080%20mg%2080%20mg)). Adding a handful of mixed nuts or seeds to your diet each day can deliver beneficial levels of vitamin E and zinc. Furthermore, using **olive oil** (another Mediterranean diet component) in place of saturated fats can reduce inflammation. Studies have found that people with high olive oil intake had lower AMD incidence, whereas those with diets high in trans-fats or highly processed snacks had higher risk of AMD. 

- **Low-Glycemic Foods**: Emerging evidence suggests that diets high in refined carbohydrates (high glycemic index) may accelerate retinal aging. High-glycemic diets can cause chronic oxidative stress and inflammation via blood sugar spikes and advanced glycation end-products. In one study, individuals with the highest dietary glycemic index had over double the rate of early AMD compared to those eating low-GI diets ([Dietary glycemic index and the risk of age-related macular ... - PubMed](https://pubmed.ncbi.nlm.nih.gov/18842800/#:~:text=PubMed%20pubmed.ncbi.nlm.nih.gov%20%20A%20high,foods%20such%20as%20oatmeal)) ([AMD & Glycemic Index | Carolinas Center for Sight](https://www.ccfs2020.com/blog/amd-glycemic-index/#:~:text=AMD%20%26%20Glycemic%20Index%20,known%20or%20suspected%20to)). Replacing white bread, sugary cereals, and other refined carbs with **low-GI alternatives** (oatmeal, whole grains, legumes) may lower this risk. This dietary pattern also stabilizes blood sugar and benefits vascular health, indirectly helping the retina. While more research is ongoing, it’s prudent to favor complex carbs and fiber for both eye and overall health.

**Lifestyle Note:** In addition to diet, it’s critical to **avoid smoking** (which injects massive oxidative stress into the retina) and to moderate alcohol intake (heavy drinking is linked to higher AMD incidence ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=calcium%20or%20lycopene))). Regular physical exercise and keeping blood pressure and cholesterol under control will support healthy blood flow to the eyes. And don’t forget UV protection – wearing sunglasses to limit UV and blue light exposure may reduce cumulative light damage to the macula over decades.

## Vitamins and Supplements Backed by Research

When diet alone isn’t enough or AMD is already diagnosed, targeted supplementation can help fill nutritional gaps. The most compelling evidence comes from the large NIH-sponsored **Age-Related Eye Disease Studies (AREDS and AREDS2)**:

- **AREDS/AREDS2 Formulation**: Researchers identified a specific high-dose vitamin/mineral mix that can slow AMD’s progression. The original AREDS formula contained **vitamin C (500 mg), vitamin E (400 IU), beta-carotene (15 mg), zinc (80 mg), and copper (2 mg)**. In a trial of 3,600 patients, this combo reduced the 5-year risk of advanced AMD by about **25%** compared to placebo ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=1,which%20increases%20lung%20cancer%20risk)). It was a breakthrough – the first evidence that nutrition could modify AMD’s course. However, beta-carotene was later dropped (due to increased lung cancer risk in smokers). The updated **AREDS2 formula** substituted **lutein (10 mg) and zeaxanthin (2 mg)** in place of beta-carotene and also tested adding omega-3s (which did not add benefit) ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=1,which%20increases%20lung%20cancer%20risk)) ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=4.%20Omega,which%20increases%20lung%20cancer%20risk)). AREDS2 proved slightly more effective than the original and is now the standard recommendation for those with intermediate or advanced dry AMD in at least one eye ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=1,which%20increases%20lung%20cancer%20risk)). Notably, AREDS supplements are **not a cure** and do not restore lost vision, but they **slow the rate of further vision loss** ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=Major%20AREDS%2FAREDS2%20findings%3A)). For individuals at risk (extensive drusen or vision loss in one eye), many eye doctors suggest an AREDS2 supplement as a preventive measure. Always consult an eye care professional before starting these high-dose vitamins. 

- **Vitamin C and E**: These antioxidants work synergistically in the eye. Vitamin C (500 mg in AREDS) regenerates vitamin E and directly quenches ROS in the aqueous fluid. Vitamin E (400 IU in AREDS) protects fatty components of cells from oxidation. Together they were shown to significantly cut AMD progression ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=1,which%20increases%20lung%20cancer%20risk)). Beyond AREDS, diets naturally high in vitamins C and E are associated with lower AMD prevalence ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=Using%20the%20Grading%20of%20Recommendations%2C,of%20early%20to%20late%20AMD)). Good sources are citrus fruits, berries, kiwifruit (for C) and nuts, seeds, wheat germ (for E). If one’s diet is lacking, a daily multivitamin or supplement providing ~500 mg C and 400 IU E can ensure adequate levels, but doses beyond these have not shown extra benefit for AMD.

- **Zinc and Copper**: Zinc was another star of the AREDS trials. At 80 mg daily, zinc oxide contributed to reduced AMD progression ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=Commercially%20available%20formulas%20based%20on,Zinc%2080%20mg%2080%20mg)). Zinc is thought to stabilize cell membranes and DNA, and it is required for the enzyme that breaks down toxic retinal byproducts. Many AMD patients have suboptimal zinc intake from diet, so supplementation helps. However, high-dose zinc can deplete copper, hence 2 mg copper was added to prevent anemia ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=Beta,Zinc%2080%20mg%2080%20mg)). In practice, most AREDS2 supplements contain the full combo of vitamins plus zinc and copper. Some newer formulations offer lower zinc (25–40 mg) if 80 mg causes stomach upset, but evidence suggests the high dose was effective. Maintaining healthy zinc levels (through oysters, meat, beans, or supplements) is an evidence-backed strategy for macular protection.

- **Lutein & Zeaxanthin Supplements**: These carotenoids, as discussed, are crucial for macular pigment. While diet is the best source, supplements can help individuals who don’t eat enough greens. AREDS2 showed that adding lutein (10 mg) and zeaxanthin (2 mg) daily improved outcomes, especially for people with low dietary intake of these carotenoids ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=4.%20Omega,which%20increases%20lung%20cancer%20risk)). Many over-the-counter eye vitamins now include 10–20 mg lutein and 2–4 mg zeaxanthin. Clinical studies indicate such supplementation can increase macular pigment density, which is thought to be protective. For example, a small trial found that **goji berries** (rich in zeaxanthin) taken regularly increased macular pigment optical density and could potentially delay AMD onset ([
            Goji Berry Intake Increases Macular Pigment Optical Density in Healthy Adults: A Randomized Pilot Trial - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC8708314/#:~:text=consumed%20either%2028%20g%20of,delay%20the%20development%20of%20AMD)). This suggests that obtaining these pigments, whether through diet or pills, helps fortify the retina. Lutein/zeaxanthin supplements are generally very safe; they can sometimes tint the skin yellow at high doses, but that’s harmless and reverses if intake is lowered.

- **B Vitamins (Folate, B6, B12)**: Interestingly, a *randomized controlled trial* in women found that daily B-vitamin supplementation significantly reduced AMD risk over 7+ years ([
            Folic Acid, Vitamin B6, and Vitamin B12 in Combination and Age-related Macular Degeneration in a Randomized Trial of Women - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC2648137/#:~:text=After%20an%20average%20of%207,CI%2C%200.36%E2%80%930.95%3B%20p%3D0.03)) ([
            Folic Acid, Vitamin B6, and Vitamin B12 in Combination and Age-related Macular Degeneration in a Randomized Trial of Women - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC2648137/#:~:text=Conclusions)). Women taking folic acid (2.5 mg), vitamin B6 (50 mg), and B12 (1 mg) had a 34% lower incidence of AMD compared to placebo ([
            Folic Acid, Vitamin B6, and Vitamin B12 in Combination and Age-related Macular Degeneration in a Randomized Trial of Women - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC2648137/#:~:text=After%20an%20average%20of%207,CI%2C%200.36%E2%80%930.95%3B%20p%3D0.03)). The mechanism is likely via reduction of homocysteine, an amino acid that at high levels can damage blood vessels (including those in the retina). High homocysteine and cardiovascular disease are linked with AMD, so lowering it with B vitamins may improve ocular blood flow and reduce endothelial dysfunction ([
            Folic Acid, Vitamin B6, and Vitamin B12 in Combination and Age-related Macular Degeneration in a Randomized Trial of Women - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC2648137/#:~:text=Recent%20cross,12%7D%20%28cyanocobalamin)) ([
            Folic Acid, Vitamin B6, and Vitamin B12 in Combination and Age-related Macular Degeneration in a Randomized Trial of Women - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC2648137/#:~:text=has%20been%20shown%20to%20reduce,are%20no%20previous%20data%20from)). While more research is needed, ensuring adequate **folate (B9)** from leafy greens and beans, **B6** from poultry, fish, bananas, and **B12** from animal products or supplements is a wise choice. A balanced diet or a B-complex vitamin can usually cover these needs. This is especially relevant for those with high homocysteine or those who have cardiovascular risk factors alongside AMD.

- **Vitamin D**: There is some evidence that low vitamin D status correlates with higher risk of macular degeneration, possibly due to vitamin D’s anti-inflammatory properties. A few observational studies suggest that people with vitamin D deficiency had greater odds of AMD, and vitamin D might help modulate the immune aspects of the disease. However, direct supplementation trials are lacking. Still, maintaining a healthy vitamin D level (through sunlight exposure or supplements of 800–1000 IU/day) is recommended for general health and may confer eye benefits. 

- **Other Antioxidants**: **Astaxanthin**, a red-orange carotenoid from algae (and found in seafood like krill or salmon), has gained attention in eye health supplements. It is a potent antioxidant that can cross into eye tissues. Lab studies indicate astaxanthin can protect retinal cells from UV-induced damage and inflammation, similar to lutein/zeaxanthin ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=cell%20layer%20from%20light,Some)). Though not part of the AREDS formula, astaxanthin is sometimes included in “vision formula” supplements at 4–12 mg doses. Similarly, **resveratrol** (discussed more in herbs/polyphenols below) is available as a supplement due to its antioxidant and antiangiogenic effects on the retina ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=specifically%20in%20disease%20prevention%20terms,human%20RPE%20cells%20in%20vitro)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=superoxide%20dismutase%20activities%20that%20lower,2%20kinase)). It’s important to note that aside from the AREDS ingredients and B vitamins, many of these newer supplements have *promising but not yet definitive* evidence. They should be considered complementary to, not replacements for, standard care.

In summary, a high-quality **eye supplement** for someone with AMD or at risk typically contains: vitamins C, E, lutein, zeaxanthin, zinc, copper, plus possibly B vitamins and other carotenoids. These are meant to “cover your bases” and provide concentrations of nutrients that diet alone might not always achieve. Always discuss with a healthcare provider before starting supplements, especially at high doses, to ensure they’re appropriate for your individual health (for example, smokers should avoid beta-carotene; people on blood thinners should use caution with high-dose vitamin E or ginkgo as discussed below).

## Herbal and Nutraceutical Therapies for AMD

Beyond standard vitamins, a number of **herbal remedies and plant-derived compounds** have a long history of use for vision and now have scientific studies supporting their role in macular health. These natural therapies often exert antioxidant, anti-inflammatory, and microcirculatory benefits – aligning perfectly with AMD’s pathogenic factors. Below are some of the most notable herbal and nutraceutical interventions:

 ([Saffron herb photo – Free Flower Image on Unsplash](https://unsplash.com/photos/saffron-herb-fRxKguqloZo)) *Herbal therapies like **saffron** (pictured: red saffron spice threads) have been used since antiquity and are now backed by clinical research for supporting retinal health in AMD.* Saffron is one of several plant-based treatments gaining recognition for macular degeneration:

- **Saffron (Crocus sativus)**: Saffron has a rich history in herbal medicine (used in ancient Greek, Persian, and Ayurvedic traditions) for ailments including eye disorders. Modern science has validated saffron’s benefits for AMD in multiple studies. Saffron contains potent carotenoid antioxidants (*crocin* and *crocetin*) that can accumulate in the retina. These compounds not only neutralize free radicals but also appear to improve **oxygen diffusion and blood flow in the retina and choroid** ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=possess%20antinflammatory%20and%20antiapoptotic%20effects%2C,exact%20mechanism%20as%20peculiar%20characteristics)). Saffron also exhibits anti-inflammatory and antiapoptotic effects – for example, it can inhibit caspase activity, thereby protecting retinal cells from programmed death after stress ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=all%20bioactive%20constituents%20should%20be,saffron%E2%80%99s%20neuroprotective%20effect%20through%20the)). Remarkably, clinical trials (including at least four RCTs) have shown that **20–50 mg of saffron daily can improve visual function in early AMD** ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=saffron%20and%20its%20components%20%28Fern%C3%A1ndez,Both)). Patients on saffron noticed improvements in contrast sensitivity and visual acuity, and some studies noted slowed progression of retinal degeneration ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=saffron%20and%20its%20components%20%28Fern%C3%A1ndez,Both)). One proposed mechanism is that saffron influences genetic expression in the retina, “turning on” protective factors (some research suggests it modulates a receptor called P2X7 and other gene pathways) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=the%20retina%20and%20choroid%2C%20factors,demonstrated%20the%20protective%20effects%20of)). Overall, saffron is emerging as a valuable adjunct therapy. It is considered safe and well-tolerated; in trials no significant adverse effects were seen aside from the expense (saffron is a costly spice). Given its multi-targeted action – antioxidant, anti-inflammatory, and circulatory – saffron supplementation is **an evidence-backed option** for patients looking to support their vision naturally ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=also%20been%20investigated%20in%20AMD,crocin%2C%20the%20synergistic%20effect%20of)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=possess%20antinflammatory%20and%20antiapoptotic%20effects%2C,exact%20mechanism%20as%20peculiar%20characteristics)). It’s important to source it from a reputable supplier to ensure purity.

- **Bilberry & Blueberry (Vaccinium berries)**: **Bilberry (Vaccinium myrtillus)** is a dark berry historically renowned for vision health – legend has it WWII pilots ate bilberry jam to improve night vision. These berries are rich in **anthocyanins**, deep-purple flavonoid pigments. While human trials in AMD are limited, lab and animal studies are promising. Anthocyanins have *affinity for retinal tissues*, particularly the RPE, and can enhance **night vision adaptation** ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=the%20eye%2C%20and%20their%20potent,its%20components%20such%20as%20malvidin)). They improve ocular blood flow and oxygen delivery and have strong antioxidant properties ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=disorders%2C%20but%20human%20data%20on,2007%29%20has)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=not%20completely%20understood,%282018%29%20demonstrated%20that%20the)). Experiments show bilberry extracts upregulate retinal antioxidant defense enzymes like HO-1 and glutathione S-transferase in RPE cells ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=retina%2C%20the%20portion%20of%20the,of%20superoxide%20dismutase%2C%20catalase%20and)). They also protect against the blue-light-induced oxidative damage by quenching singlet oxygen, thereby preventing lipofuscin (A2E) from harming the retina ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=glutathione%20peroxidase%20in%20human%20retinal,be%20an%20important%20factor%20in)). In an accelerated aging rat model, long-term bilberry supplementation *completely prevented* the development of macular degeneration changes seen in control rats ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=shown%20that%20anthocyanins%20from%20blueberries,demonstrated%20that%20bilberry%20extract%20attenuates)). Additionally, bilberry extract reduced light-induced apoptosis (cell death) in a mouse retina study ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=stress%2C%20was%20effective%20in%20preventing,main%20complication%20for%20the%20clinical)). All of this mechanistic evidence suggests bilberry’s anthocyanins could slow AMD. Clinically, bilberry is available as supplements (typically 80–160 mg of extract standardized to 25% anthocyanins). Though “hard proof” in humans is pending, many patients and practitioners use bilberry as a supportive therapy. It also helps strengthen capillaries (which can be beneficial in diabetic retinopathy and possibly wet AMD to reduce hemorrhages). Eating blueberries and other dark berries regularly is another way to obtain these compounds. They are delicious and nutritious, so there’s little downside – except perhaps cost for the supplements. Those on bilberry should just be aware of the lack of large human trials and use it as a complement to, not a substitute for, conventional treatments.

- **Ginkgo biloba**: **Ginkgo** is one of the oldest living tree species and has been used in Traditional Chinese Medicine for centuries, particularly for blood circulation and cognitive support. Ginkgo leaf extracts (like the standardized EGb 761) contain **flavonoids (quercetin, kaempferol glycosides)** and **terpene lactones (ginkgolides, bilobalide)**, which collectively have neuroprotective and vasodilatory effects ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=Mojaverrostami%20et%20al,the%20antioxidant%20and%20radical%20scavenging)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=2013%29,are%20hypothesized%20as%20potential%20mechanisms)). In the context of AMD, ginkgo’s benefits come from improving **microcirculation in the ocular tissues** and providing antioxidant protection. The flavonoids in ginkgo scavenge free radicals and reduce oxidative damage to retinal cell membranes ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=standardised%20preparations%20EGb%20761%20and,extract%20has%20aroused%20for%20AMD)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=properties%20of%20ginkgo%20flavonoids%20and,however%2C%20the%20increased%20risk%20of)). Meanwhile, ginkgolides are platelet-activating factor (PAF) antagonists, which means they reduce blood viscosity and the tendency of blood to clot, thereby enhancing blood flow through tiny capillaries ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=quenching%20properties%2C%20reduction%20of%20platelet,extract%20has%20aroused%20for%20AMD)). This is particularly relevant in AMD where choroidal circulation impairment is an issue. Small clinical studies (including two randomized trials) have reported **improved visual acuity and slow visual field loss** in AMD patients taking ginkgo extract (typically 120–160 mg/day) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=%28Evans%2C%202013%29,efficacy%20should%20be%20carried%20out)). A Cochrane review noted some positive trends and called for more research, but ginkgo is considered generally safe for AMD patients ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=vascular%20factors%20and%20oxidative%20damage,clinical%20studies%20have%20investigated%20the)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=Martinez,efficacy%20should%20be%20carried%20out)). Caution is advised for those on blood thinners, since ginkgo’s anti-platelet effect could slightly increase bleeding risk (e.g., rare reports of nosebleeds or prolonged bleeding cuts) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=treatment,According)). Overall, **ginkgo can be a useful adjunct** to support retinal circulation and antioxidant defenses. It is relatively inexpensive and widely available. Patients should use standardized extracts and let their doctors know, especially before any surgeries or if they have bleeding disorders.

- **Turmeric (Curcumin)**: Turmeric root (Curcuma longa) is a spice with a long history in Ayurvedic medicine for treating inflammation. Its active ingredient **curcumin** has drawn attention for eye diseases including AMD. Curcumin is a multi-targeted molecule: it’s a strong anti-inflammatory, antioxidant, and even anti-angiogenic agent ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=inflammatory%20and%20degenerative%20retinal%20eye,reported%20that%20curcumin%20activates)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=molecular%20targets.%20It%20exerts%20anti,9%20causes%20extracellular%20matrix)). In retinal cells, curcumin has been shown to **activate PPAR-γ**, a receptor that downregulates inflammation and may inhibit abnormal blood vessel growth in wet AMD ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=antiangiogenic%20properties%20through%20the%20modulation,to%20Bruch%E2%80%99s%20membrane%2C%20and%20thus)). By activating PPAR-γ, curcumin can suppress *VEGF* and *MMP-9* production – VEGF is the signal that causes new vessel formation, and MMP-9 facilitates tissue breakdown leading to neovascularization ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=proliferator,significant%20protection%20against%20photooxidative%20damage)). Thus, curcumin could theoretically help in both dry AMD (reducing chronic inflammation) and wet AMD (reducing angiogenesis). Lab studies back this up: curcumin protected RPE cells loaded with A2E (a toxic pigment) from light-induced damage and oxidative stress ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=degradation%20and%20stimulates%20RPE%20cell,this%20compound%20is%20similar%20to)). It also upregulated antioxidant enzymes like HO-1 in cell culture and protected retinal neurons in animal models by inhibiting NF-κB (a master inflammation switch) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=mechanisms.%20The%20anti,the%20biomedical%20potential%20of%20curcumin)). The challenge with curcumin is **bioavailability** – it doesn’t absorb well when taken orally. However, new formulations (with piperine from black pepper, nanoparticle curcumin, or curcumin-phospholipid complexes) greatly enhance absorption ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=cells%20from%20H_%7B2%7DO_%7B2%7D,Basnet%2C%202011)). Early pilot studies in humans are exploring curcumin for AMD, but as of now, evidence is mostly preclinical. That said, many integrative physicians recommend 500–1000 mg/day of a curcumin extract for patients with retinal inflammatory conditions, given its excellent safety profile (doses up to 8 g/day for 3 months showed no major toxicity ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=Improving%20the%20pharmacological%20profile%20by,Basnet%2C%202011))). If a patient enjoys cooking, using turmeric spice liberally (with a pinch of black pepper and some fat to aid absorption) is another way to include curcumin in the diet. While not yet a proven AMD treatment, **curcumin holds promise** as a supportive therapy and certainly won’t harm when used appropriately.

- **Goji Berries (Lycium barbarum)**: A cornerstone of Traditional Chinese Medicine for vision is the goji berry (also known as wolfberry). In Chinese lore, goji is said to “brighten the eyes,” and modern research lends some support to this claim. Goji berries are extremely high in **zeaxanthin** – one of the highest natural sources known – as well as other antioxidants like vitamin C and polysaccharides beneficial to the immune system. A recent randomized trial in healthy adults ages 45-65 found that eating a small serving of goji berries (28 grams, about a small handful) five days a week for 90 days **significantly increased macular pigment density**, compared to a control group that took a standard lutein/zeaxanthin supplement ([
            Goji Berry Intake Increases Macular Pigment Optical Density in Healthy Adults: A Randomized Pilot Trial - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC8708314/#:~:text=and%20zeaxanthin%20,berry%20group%20at%20day%2045)) ([
            Goji Berry Intake Increases Macular Pigment Optical Density in Healthy Adults: A Randomized Pilot Trial - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC8708314/#:~:text=consumed%20either%2028%20g%20of,delay%20the%20development%20of%20AMD)). The goji group’s macular pigment (L and Z levels in the retina) improved, suggesting that regular goji consumption could help *prevent or delay AMD development* ([
            Goji Berry Intake Increases Macular Pigment Optical Density in Healthy Adults: A Randomized Pilot Trial - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC8708314/#:~:text=consumed%20either%2028%20g%20of,delay%20the%20development%20of%20AMD)). This effect is likely due to the bioavailable zeaxanthin and perhaps synergistic nutrients in the whole fruit. Another study on patients with early AMD found goji supplementation increased zeaxanthin levels and macular pigment as well ([Macular pigment and serum zeaxanthin levels with Goji berry ...](https://www.semanticscholar.org/paper/Macular-pigment-and-serum-zeaxanthin-levels-with-in-Li-Liu/828319c0b60b3e528023f27b96bf0d091023c7fa#:~:text=Macular%20pigment%20and%20serum%20zeaxanthin,AMD%20patients%2C%20and%20may)). Beyond carotenoids, goji berries have compounds that may protect retinal ganglion cells and prevent hypopigmentation of the macula (as seen in animal models). For practical use, goji berries can be eaten raw, added to trail mix, or brewed as tea. They have a pleasant sweet taste. In dried form they resemble red raisins. A typical “dose” in herbal medicine is 20–30 berries a day. As an easy dietary addition, **goji berries are a credible functional food for eye health** – and they connect modern science with an ancient herbal tradition.

- **Resveratrol and Grape Seed Extract**: Resveratrol is a polyphenol most famously found in red wine (from grape skins). It gained fame for heart health, but it also has intriguing effects in the eye. Lab studies suggest resveratrol can **re-establish healthy architecture in the retina, reduce lipofuscin accumulation, improve choroidal blood perfusion, and enhance macular pigment** ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=specifically%20in%20disease%20prevention%20terms,human%20RPE%20cells%20in%20vitro)). It has been shown to protect RPE cells from oxidative damage and to *inhibit abnormal angiogenesis* by downregulating factors like VEGF and inflammatory cytokines ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=superoxide%20dismutase%20activities%20that%20lower,2%20kinase)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=late,secretion%20and%20migration%20by%20a)). In models of choroidal neovascularization (wet AMD), resveratrol reduced the growth of those blood vessels via multiple pathways – blocking HIF-1α (a hypoxia signal) and activating eukaryotic factor-2 kinase which leads to less endothelial proliferation ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=late,secretion%20and%20migration%20by%20a)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=cells%20this%20confirms%20RV%20can,It%20has%20a%20significant)). Additionally, resveratrol supports mitochondrial health in retinal cells, which is crucial in aging conditions ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=and%20to%20reduce%20endothelial%20cell,RV)). While these findings are mostly from in vitro or animal work, they indicate resveratrol could be beneficial against both atrophic and neovascular AMD processes. Some eye supplements include resveratrol (often 50–100 mg dosage). Separately, **grape seed extract**, rich in proanthocyanidins, is another product from grapes that has antioxidant and vasoprotective effects; it hasn’t been studied as much in AMD specifically, but it can support capillary strength. Moderate intake of red wine in a Mediterranean diet context might also confer some resveratrol – though one must balance this with the fact that excessive alcohol is harmful to eyes. For those who prefer not to drink, resveratrol supplements or simply eating grapes/blueberries could be considered. It’s an active area of research, and some ophthalmologists are excited about the potential of **resveratrol as a neuroprotective agent for the retina** ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=specifically%20in%20disease%20prevention%20terms,human%20RPE%20cells%20in%20vitro)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=The%20review%20by%20Abu,are%20many%20in%20vitro%20studies)).

- **Green Tea (EGCG)**: Green tea contains catechins, notably **EGCG**, which are powerful antioxidants and anti-inflammatory compounds. While not a traditional “herb for eyes,” green tea consumption has been associated with various health benefits. Catechins from green tea do reach the eye; a study detected green tea catechins in animal retinal tissue after ingestion, and they provided antioxidant protection. Polyphenols in green tea can help quench ROS and chelate metal ions that generate free radicals ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=Polyphenols%20represent%20a%20large%20group,eye%20diseases%20are%20listed%20below)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=coffee,eye%20diseases%20are%20listed%20below)). Additionally, green tea may help modulate angiogenic factors. Although there isn’t direct clinical evidence that “drinking green tea cures AMD,” incorporating green or white tea into one’s diet is a simple, safe way to boost overall antioxidant capacity. Many “eye health” herbal blends include green tea or grape seed extract along with the above-mentioned herbs.

- **Others**: A few other herbal considerations include **Milk Thistle (silymarin)**, which may protect retinal cells by supporting liver function and antioxidant status; **Gingko (covered above)**; and some Chinese herbal formulas (for example, a TCM formula called *Mingmu Dihuang Wan* is traditionally used for retinal degeneration, containing goji, chrysanthemum, rehmannia, etc., though clinical evidence is sparse). In Ayurveda, **Triphala** (an herbal rasayana blend) is sometimes used for eye health as a tonic. These are ancillary and not as well researched, so if used, it should be under guidance of a knowledgeable practitioner.

### Mechanisms of Action

What do these diverse nutrients and herbs have in common? Most exert one or more of the following effects that counter AMD’s causes:

- **Antioxidant Activity**: Nearly all the interventions – vitamins C and E, carotenoids (lutein/zeaxanthin, astaxanthin), polyphenols (anthocyanins, resveratrol), turmeric, saffron, green tea, etc. – help neutralize ROS in the retina. This directly combats the oxidative stress that drives retinal damage ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=Most%20studies%20indicate%20that%20saffron,have%20reported%20that%20saffron%20components)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=blueberry%20anthocyanin%20extract%2C%20and%20some,A2E%20cannot%20be%20enzymatically%20degraded)). By reducing lipid peroxidation and DNA damage in RPE cells, these agents slow the accumulation of cellular debris (like drusen) and preserve cell function. Some, like macular carotenoids and anthocyanins, also absorb blue light or quench singlet oxygen, preventing those high-energy photons from creating free radicals in the first place ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=glutathione%20peroxidase%20in%20human%20retinal,be%20an%20important%20factor%20in)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=level%20%28Bungau%20et%20al,has%20been%20reported%20that%20lutein)).

- **Anti-Inflammatory Effects**: Chronic low-level inflammation in AMD can be mitigated by many of these compounds. Omega-3 fatty acids yield less inflammatory prostaglandins; vitamin D and curcumin downregulate inflammatory cytokines; resveratrol and green tea inhibit NF-κB (an inflammatory transcription factor) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=superoxide%20dismutase%20activities%20that%20lower,2%20kinase)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=mechanisms.%20The%20anti,the%20biomedical%20potential%20of%20curcumin)). Saffron has demonstrated inhibition of retinal inflammation and even modulates immune purinergic receptors related to inflammation ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=the%20retina%20and%20choroid%2C%20factors,demonstrated%20the%20protective%20effects%20of)). Reducing inflammation helps slow damage to the RPE and choroid, and may also reduce stimulation for new blood vessel growth.

- **Support of Retinal Circulation**: Several interventions improve blood flow or vascular health. Ginkgo’s flavonoids dilate blood vessels and its ginkgolides reduce blood viscosity ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=quenching%20properties%2C%20reduction%20of%20platelet,extract%20has%20aroused%20for%20AMD)). Omega-3s make blood less “sticky” and improve endothelial function. Saffron was shown to increase retinal and choroidal blood flow (crocetin in saffron may act as a vasodilator) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=possess%20antinflammatory%20and%20antiapoptotic%20effects%2C,exact%20mechanism%20as%20peculiar%20characteristics)). B-vitamin therapy lowers homocysteine, thereby improving endothelial health and reducing the risk of thrombotic micro-occlusions in retinal vessels ([
            Folic Acid, Vitamin B6, and Vitamin B12 in Combination and Age-related Macular Degeneration in a Randomized Trial of Women - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC2648137/#:~:text=Recent%20cross,12%7D%20%28cyanocobalamin)) ([
            Folic Acid, Vitamin B6, and Vitamin B12 in Combination and Age-related Macular Degeneration in a Randomized Trial of Women - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC2648137/#:~:text=has%20been%20shown%20to%20reduce,are%20no%20previous%20data%20from)). Better circulation means more oxygen and nutrient delivery and more efficient removal of waste from the retinal tissues, slowing atrophy.

- **Neuroprotection**: The photoreceptors and retinal neurons can be considered brain tissue (as the retina is an extension of the central nervous system). Many herbs act as neuroprotectants. For example, saffron’s crocin and crocetin protect photoreceptors from light-induced death and preserve their response to stimuli ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=all%20bioactive%20constituents%20should%20be,saffron%E2%80%99s%20neuroprotective%20effect%20through%20the)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=mechanism%20responsible%20for%20saffron%E2%80%99s%20neuroprotective,2012%3B%20Di%20Marco%20et%20al)). Curcumin’s ability to inhibit apoptosis in retinal cells under stress is another neuroprotective action ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=mechanisms.%20The%20anti,the%20biomedical%20potential%20of%20curcumin)). Lutein and zeaxanthin, by embedding in cell membranes, make photoreceptors more resilient to stress. These help keep retinal cells alive and functioning longer despite the insults of aging.

- **Anti-angiogenic Properties**: In advanced (wet) AMD, preventing unwanted blood vessel growth is key. While medical injections (anti-VEGF drugs) are mainstay for wet AMD, some nutraceuticals may support this goal. Resveratrol has been noted to inhibit pathological angiogenesis via multiple pathways (VEGF suppression, etc.) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=superoxide%20dismutase%20activities%20that%20lower,2%20kinase)). Curcumin, as noted, activates PPAR-γ and directly lowers pro-angiogenic factors ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=proliferator,significant%20protection%20against%20photooxidative%20damage)). Omega-3 DHA was reported in some studies to reduce aberrant angiogenesis in animal eyes, possibly by resolving inflammation. Though these are not replacements for medical therapy in wet AMD, they might contribute to a holistic approach that keeps the environment of the eye less conducive to neovascularization.

- **Pigment and Light Filtration**: Unique to the macular carotenoids (lutein, zeaxanthin, meso-zeaxanthin) is the ability to form a yellow pigment shield in the macula that filters out harmful blue-violet light. By absorbing these wavelengths, the macular pigment prevents high-energy light from reaching the vulnerable photoreceptors and RPE, thereby reducing photo-oxidative stress ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=level%20%28Bungau%20et%20al,has%20been%20reported%20that%20lutein)). Goji berries, by raising macular pigment, enhance this natural shield ([
            Goji Berry Intake Increases Macular Pigment Optical Density in Healthy Adults: A Randomized Pilot Trial - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC8708314/#:~:text=and%20zeaxanthin%20,berry%20group%20at%20day%2045)) ([
            Goji Berry Intake Increases Macular Pigment Optical Density in Healthy Adults: A Randomized Pilot Trial - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC8708314/#:~:text=consumed%20either%2028%20g%20of,delay%20the%20development%20of%20AMD)). This mechanism is highly specific but important – it’s like internal “sunglasses” for the retina and is a key reason why boosting macular pigment via diet or supplements is recommended.

Each intervention may work via one or multiple of these mechanisms. The **combined effect** of a healthy diet plus selective supplements and herbs can create a retinal environment rich in protective factors and low in damaging factors, effectively slowing the degenerative process of AMD.

## Practical Recommendations for Patients

In light of the above, here are practical, evidence-based steps a person concerned about AMD can take:

- **Eat a Rainbow of Produce Daily** – Focus on **dark leafy greens** (spinach, kale, collards) and **brightly colored fruits/veggies** (bell peppers, carrots, oranges, berries). These provide lutein, zeaxanthin, vitamin C, beta-carotene, and flavonoids that have been tied to lower AMD risk ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=Using%20the%20Grading%20of%20Recommendations%2C,of%20early%20to%20late%20AMD)). For example, include a large leafy salad or green smoothie, and sides like steamed spinach or kale chips. Snack on berries or an orange instead of sweets. Aim for at least 5 servings of fruits and vegetables per day, with 2–3 of those being rich in carotenoids. This mirrors a Mediterranean-style diet, which studies show can reduce the likelihood of AMD progressing ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=In%20addition%2C%20use%20of%20antioxidant,intake%20of%20calcium%20or%20lycopene)).

- **Get Your Omega-3s** – Incorporate **fatty fish** into your meals a couple of times a week. A serving of salmon, tuna, sardines or trout provides high levels of DHA and EPA, which help tamp down retinal inflammation and support cell structure ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=Using%20the%20Grading%20of%20Recommendations%2C,of%20early%20to%20late%20AMD)). If you don’t eat fish, consider an omega-3 supplement (like fish oil or algae-based DHA) after consulting your doctor – though note that supplements haven’t conclusively shown the same benefit as fish-rich diets ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=2,which%20increases%20lung%20cancer%20risk)). Additionally, include some **nuts and seeds** (e.g. walnuts, flaxseed, chia) in your diet for plant-based omega-3 (ALA) and vitamin E. For instance, sprinkle ground flax or chia on yogurt or oatmeal, or have a small handful of walnuts as a snack.

- **Consider an Eye-Specific Multivitamin** – If you have intermediate AMD or extensive drusen, talk to your ophthalmologist about taking an **AREDS2 formula** supplement. This high-dose combination of vitamins C & E, lutein (10 mg), zeaxanthin (2 mg), zinc (~25–80 mg), and copper is *clinically proven* to slow AMD’s progression ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=1,which%20increases%20lung%20cancer%20risk)). It’s available over the counter in products like PreserVision or other brands. Generally, one would take two capsules per day with food. Importantly, if you are (or were) a smoker, ensure the formula is beta-carotene free (most AREDS2 formulas are, using lutein/zeaxanthin instead, to avoid any lung risk) ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=4.%20Omega,which%20increases%20lung%20cancer%20risk)). For those without diagnosed AMD but who have family history or are simply proactive, a daily **lutein (10 mg) + zeaxanthin (2 mg)** supplement is safe and may help, especially if vegetable intake is low. Many general multivitamins don’t contain these in high amounts, so an “eye vitamin” is useful. Remember supplements are *supplemental* – they work best alongside a good diet, not in place of one.

- **Include Herbal Allies (with Professional Guidance)** – Supplements like **saffron (20 mg)** or **bilberry extract (80–160 mg)** can be considered as adjuncts to your regimen, given the encouraging research. Saffron in particular has human clinical data showing visual improvements ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=saffron%20and%20its%20components%20%28Fern%C3%A1ndez,Both)). One might take 20 mg of saffron daily (often available in vision supplements or as standalone capsules). Bilberry can be taken as a capsule or by simply eating blueberries frequently. **Ginkgo biloba (120 mg)** standardized extract is another option to discuss with your doctor, especially if poor circulation or cognitive issues are also present – it could modestly improve blood flow to the eyes ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=%28Evans%2C%202013%29,efficacy%20should%20be%20carried%20out)). These herbal supplements are available at health stores; ensure you choose high-quality products (look for ones tested for purity). It’s wise to add one new supplement at a time and monitor for any side effects. For example, start saffron for a few months and see how you feel (and ideally have regular eye exams to monitor any changes). Always inform your eye specialist about any herbal pills you’re taking.

- **Maintain a Healthy Lifestyle** – The health of your eyes is connected to the health of your whole body. Key lifestyle tips include: **Don’t smoke** (smoking increases AMD risk up to 4-fold and accelerates vision loss – quitting at any stage will help preserve your sight). **Exercise regularly** – activities like walking, swimming, or yoga improve cardiovascular health and thereby retinal perfusion. **Keep blood pressure and cholesterol in check**, through diet, exercise, and medications if needed; hypertension and atherosclerosis can worsen AMD by harming retinal vessels. **Manage body weight and blood sugar** – obesity and diabetes add oxidative stress and inflammation, so weight loss and glucose control can be protective for your eyes too. Limit **alcohol** to moderate levels (excessive drinking is tied to higher AMD risk ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=calcium%20or%20lycopene)), whereas light-to-moderate intake, especially of red wine in a diet context, might be neutral or even beneficial due to resveratrol – but moderation is key). Lastly, **protect your eyes from excessive light**: wear UV-blocking sunglasses and a hat in bright sun; consider blue-light-filtering lenses if you spend long hours on screens (though the jury is out on how much screens contribute to AMD, minimizing unnecessary blue light can’t hurt given lab evidence of blue light’s impact on retinal cells).

- **Regular Eye Check-ups** – While not a “nutritional” tip, this is vital. See your optometrist or ophthalmologist as recommended (usually yearly if you have AMD or risk factors). They can monitor drusen, macular pigment changes, and vision, and intervene with treatments (like anti-VEGF injections for wet AMD) at the earliest sign of progression. Early detection of any change allows for timely management – for instance, if your dry AMD is worsening, your doctor might reinforce supplement use or consider investigational therapies; if wet AMD develops, prompt injections can save central vision. Also, ask your eye doctor about **Amsler grid** testing at home – it’s a simple grid you look at to check for any new distortion in your vision, which can signal the onset of wet AMD.

By integrating these diet and lifestyle approaches, patients can take an active role in their eye health. AMD may not be curable yet, but its progression is often like a slow fire – with the right “extinguishers” (antioxidants, anti-inflammatories) and by removing the “fuel” (smoking, poor diet), we can significantly dampen the flames. In summary, **eat smart, supplement wisely, and live healthy** – your eyes will thank you, and you’ll improve your overall well-being in the process. With these strategies, many AMD patients are able to preserve their vision and maintain a high quality of life far longer than was possible in the past ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=The%20nutrition%20and%20supplement%20industry,in%20managing%C2%A0progression%20of%20the%20disease)) ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=research%20has%20shown%20that%20intake,in%20managing%C2%A0progression%20of%20the%20disease)).

**Sources:**

1. Ruan, Y., et al. (2021). *Age-Related Macular Degeneration: Role of Oxidative Stress and Blood Vessels.* **PMID:** 33525498 ([
            Age-Related Macular Degeneration: Role of Oxidative Stress and Blood Vessels - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7866075/#:~:text=Age,for%20patients%20suffering%20from%20AMD)) ([
            Age-Related Macular Degeneration: Role of Oxidative Stress and Blood Vessels - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7866075/#:~:text=Many%20risk%20factors%20are%20related,Oxidative%20stress%20plays%20an))  
2. Pameijer, E.M., et al. (2022). “Nutrition and the Progression of AMD” – *Acta Ophthalmologica* (review summary) ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=Using%20the%20Grading%20of%20Recommendations%2C,of%20early%20to%20late%20AMD)) ([
	Adherence to Mediterranean diet may decrease risk for AMD progression
](https://www.healio.com/news/optometry/20230216/adherence-to-mediterranean-diet-may-decrease-risk-for-amd-progression#:~:text=In%20addition%2C%20use%20of%20antioxidant,intake%20of%20calcium%20or%20lycopene))  
3. NEI – Age-Related Eye Disease Studies (AREDS/AREDS2) Clinical Trials, National Eye Institute ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=1,which%20increases%20lung%20cancer%20risk)) ([AREDS/AREDS2 Clinical Trials | National Eye Institute](https://www.nei.nih.gov/research/clinical-trials/age-related-eye-disease-studies-aredsareds2/about-areds-and-areds2#:~:text=Commercially%20available%20formulas%20based%20on,Zinc%2080%20mg%2080%20mg))  
4. Christen, W., et al. (2009). *Folic Acid, Vitamin B6, and B12 in Combination and Age-related Macular Degeneration in Women.* **Arch Intern Med**;169(4):335-41 ([
            Folic Acid, Vitamin B6, and Vitamin B12 in Combination and Age-related Macular Degeneration in a Randomized Trial of Women - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC2648137/#:~:text=After%20an%20average%20of%207,CI%2C%200.36%E2%80%930.95%3B%20p%3D0.03)) ([
            Folic Acid, Vitamin B6, and Vitamin B12 in Combination and Age-related Macular Degeneration in a Randomized Trial of Women - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC2648137/#:~:text=Conclusions))  
5. Martínez-Solís, I., et al. (2020). *Medicinal plants and natural products as neuroprotective agents in AMD.* **Neural Regen Res.** 15(3):461-470 ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=possess%20antinflammatory%20and%20antiapoptotic%20effects%2C,exact%20mechanism%20as%20peculiar%20characteristics)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=saffron%20and%20its%20components%20%28Fern%C3%A1ndez,Both)) (covers saffron, ginkgo, bilberry, curcumin, etc.)  
6. Yu, Y., et al. (2021). *Goji Berry Intake Increases Macular Pigment Optical Density in Healthy Adults: A Randomized Trial.* **Nutrients** 13(1):230 ([
            Goji Berry Intake Increases Macular Pigment Optical Density in Healthy Adults: A Randomized Pilot Trial - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC8708314/#:~:text=and%20zeaxanthin%20,berry%20group%20at%20day%2045)) ([
            Goji Berry Intake Increases Macular Pigment Optical Density in Healthy Adults: A Randomized Pilot Trial - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC8708314/#:~:text=consumed%20either%2028%20g%20of,delay%20the%20development%20of%20AMD))  
7. Babai, N., et al. (2010). “Resveratrol in Ocular Health” – *Nutrients* 12(9): in press (resveratrol’s retinal effects) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=specifically%20in%20disease%20prevention%20terms,human%20RPE%20cells%20in%20vitro)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=superoxide%20dismutase%20activities%20that%20lower,2%20kinase))  
8. Evans, J. (2013). *Cochrane Review: Ginkgo biloba for AMD* – reported some visual acuity improvements in small trials ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=vascular%20factors%20and%20oxidative%20damage,clinical%20studies%20have%20investigated%20the)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=%28Evans%2C%202013%29,efficacy%20should%20be%20carried%20out))  
9. Buscemi, S., et al. (2018). “Carotenoids and Retinal Disease” – *Nutrients* 10(1): E119 (macular pigment details) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=tissues%20and%20biological%20fluids,activities%20and%20functions%2C%20which%20are)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=level%20%28Bungau%20et%20al,has%20been%20reported%20that%20lutein))  
10. Huang, R., et al. (2018). “Anthocyanins in Blueberries Protect Retinal Cells” – *Mol Vis* 24:627-636 ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=light%20and%20dark%20,One%20cause%20of)) ([
            Medicinal plants and natural products as neuroprotective agents in age-related macular degeneration - PMC
        ](https://pmc.ncbi.nlm.nih.gov/articles/PMC7749482/#:~:text=blueberry%20anthocyanin%20extract%2C%20and%20some,A2E%20cannot%20be%20enzymatically%20degraded))  

